---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes 

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes 

- name: "Install uzip package"
  become: yes
  apt:
    name: ["unzip"]
    state: latest
    update_cache: yes

# - name: "copy eks deployment file"
#   become: true
#   copy:
#     src: eks-app-deploy.yml
#     dest: /home/ubuntu/

# - name: "copy eks app service file"
#   become: true
#   copy:
#     src: eks-app-service.yml
#     dest: /home/ubuntu/

- name: "Install AWS CLI"
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
    aws --version

    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    kubectl version --client --output=yaml   

    curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
    sudo mv /tmp/eksctl /usr/local/bin
    eksctl version

    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh ./get-docker.sh
    docker --version

...