Description: >
  server backend.

Parameters:
  EnvironmentName:
    Description: "PH CICD"
    Type: String
  AMItoUse:
    Description: "Amazon Linux AMI"
    Type: String
  InstanceType:
    Description: "Instance type to use"
    Type: String
  PublicSubnet01:
    Description: "Instance Puclic Subnet 01"
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SG-CICD
      GroupDescription: Allow port 22.
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0       

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: phuynh-cicd-ec2
      ImageId: !Ref AMItoUse
      SubnetId: 
        - Fn::ImportValue: !Sub ${EnvironmentName}-PUB1-SN
      
      Tags:
        - Key: Name
          Value: qa-ec2-cicd
