
version: 2.1

jobs:
  build:
    docker:    
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}            
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint to lint Dockerfile
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      
      - run:
          name: Run Code Linting
          command: |
            . venv/bin/activate
            make lint           
      - run:
          name: Run Pytest
          command: |
            . venv/bin/activate
            make test           

  create_image:
    docker:
      - image: cimg/base:2023.02
    steps:
      - checkout
      - run:
          name: Create Container Image
          command: |
            docker build -t sklearn-app:v1.0.0 .
            docker tag sklearn-app:v1.0.0 peterhuynh99/projectapp:v1.0.0
            docker push peterhuynh99/projectapp:v1.0.0

workflows:
  default:
    jobs:
      - build
      - create_image:
          requires: [build]