---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes 

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes 

- name: "Install uzip package"
  become: yes
  apt:
    name: ["unzip"]
    state: latest
    update_cache: yes

- name: "Create EKS Cluster"
  shell: |
    eksctl create cluster --name ph-cf-eks --region us-west-2 --node-type t2.large --nodes-min 2 --nodes-max 2
    

...