apiVersion: v1
kind: Service
metadata:
  name: ph-app-service
  labels:
    app: ph-app-project
spec:
  selector:
    app: ph-app-project
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 80
      nodePort: 33300
